export const categoryIngredientMap = {
  vodka: ['vodka'],
  rum: ['rum', 'white rum', 'dark rum', 'light rum', 'spiced rum'],
  gin: ['gin'],
  whiskey: ['whiskey', 'bourbon', 'scotch', 'irish whiskey', 'rye whiskey', 'canadian whisky'],
  tequila: ['tequila', 'mezcal'],
  liqueur: [
    'triple sec',
    'cointreau',
    'grand marnier',
    'campari',
    'aperol',
    'amaretto',
    'baileys',
    'kahlua',
    'chambord',
    'midori',
    'blue curacao',
    'galliano',
    'frangelico',
    'benedictine',
    'chartreuse',
    'drambuie',
    'irish cream',
    'coffee liqueur',
    'orange liqueur',
    'almond liqueur',
    'herbal liqueur',
    'anise liqueur',
    'cherry liqueur',
    'raspberry liqueur',
    'melon liqueur',
    'peach liqueur',
    'apricot liqueur',
    'blackberry liqueur',
    'coconut liqueur',
    'hazelnut liqueur',
    'coffee liqueur',
    'chocolate liqueur',
    'vanilla liqueur',
    'mint liqueur',
    'ginger liqueur',
    'honey liqueur',
    'maple liqueur',
    'caramel liqueur',
    'butterscotch liqueur',
    'toffee liqueur',
    'cinnamon liqueur',
    'nutmeg liqueur',
    'clove liqueur',
    'allspice liqueur',
    'cardamom liqueur',
    'saffron liqueur',
    'lavender liqueur',
    'rose liqueur',
    'elderflower liqueur',
    'hibiscus liqueur',
    'jasmine liqueur',
    'chamomile liqueur',
    'lemongrass liqueur',
    'ginger liqueur',
    'wasabi liqueur',
    'sake',
    'soju',
    'schnapps',
    'pisco',
    'cachaça',
    'absinthe',
    'pastis',
    'ouzo',
    'arak',
    'raki',
    'sambuca',
    'jägermeister',
    'fernet',
    'becherovka',
    'kummel',
    'aquavit',
    'akvavit',
    'brennivín',
    'krupnik',
    'krupnikas',
    'nalewka',
    'nalivka',
    'rakia',
    'slivovitz',
    'tsipouro',
    'tsikoudia',
    'zivania',
    'grappa',
    'marc',
    'pomace',
    'brandy',
    'cognac',
    'armagnac',
    'calvados',
    'pisco',
    'aguardiente',
    'cachaça',
    'rum',
    'rhum',
    'ron',
    'cachaça',
    'mezcal',
    'tequila',
    'vodka',
    'gin',
    'genever',
    'jenever',
    'whiskey',
    'whisky',
    'bourbon',
    'scotch',
    'irish whiskey',
    'canadian whisky',
    'rye whiskey',
    'tennessee whiskey',
    'corn whiskey',
    'malt whiskey',
    'grain whiskey',
    'blended whiskey',
    'single malt',
    'single grain',
    'blended malt',
    'blended grain',
    'cask strength',
    'single cask',
    'small batch',
    'straight whiskey',
    'bottled in bond',
    'sour mash',
    'sweet mash',
    'high rye',
    'high corn',
    'wheated',
    'peated',
    'unpeated',
    'peated malt',
    'peated grain',
    'peated blend',
    'peated single malt',
    'peated single grain',
    'peated blended malt',
    'peated blended grain',
    'peated cask strength',
    'peated single cask',
    'peated small batch',
    'peated straight',
    'peated bottled in bond',
    'peated sour mash',
    'peated sweet mash',
    'peated high rye',
    'peated high corn',
    'peated wheated',
    'peated bourbon',
    'peated scotch',
    'peated irish',
    'peated canadian',
    'peated rye',
    'peated tennessee',
    'peated corn',
    'peated malt',
    'peated grain',
    'peated blended',
    'peated single',
    'peated cask',
    'peated batch',
    'peated straight',
    'peated bond',
    'peated mash',
    'peated rye',
    'peated corn',
    'peated wheat',
    'peated barley',
    'peated oats',
    'peated rice',
    'peated quinoa',
    'peated amaranth',
    'peated buckwheat',
    'peated millet',
    'peated sorghum',
    'peated spelt',
    'peated kamut',
    'peated farro',
    'peated emmer',
    'peated einkorn',
    'peated durum',
    'peated semolina',
    'peated bulgur',
    'peated couscous',
    'peated polenta',
    'peated grits',
    'peated masa',
    'peated cornmeal',
    'peated cornstarch',
    'peated corn syrup',
    'peated corn oil',
    'peated corn flour',
    'peated corn gluten',
    'peated corn protein',
    'peated corn fiber',
    'peated corn sugar',
    'peated corn alcohol',
    'peated corn spirit',
    'peated corn liquor',
    'peated corn whiskey',
    'peated corn vodka',
    'peated corn gin',
    'peated corn rum',
    'peated corn tequila',
    'peated corn mezcal',
    'peated corn brandy',
    'peated corn cognac',
    'peated corn armagnac',
    'peated corn calvados',
    'peated corn pisco',
    'peated corn aguardiente',
    'peated corn cachaça',
    'peated corn liqueur',
    'peated corn schnapps',
    'peated corn sake',
    'peated corn soju',
    'peated corn shochu',
    'peated corn baijiu',
    'peated corn huangjiu',
    'peated corn makgeolli',
    'peated corn cheongju',
    'peated corn soju',
    'peated corn sake',
    'peated corn shochu',
    'peated corn baijiu',
    'peated corn huangjiu',
    'peated corn makgeolli',
    'peated corn cheongju',
    'peated corn soju',
    'peated corn sake',
    'peated corn shochu',
    'peated corn baijiu',
    'peated corn huangjiu',
    'peated corn makgeolli',
    'peated corn cheongju',
  ],
};
