export const categoryIngredientMap = {
  vodka: ['vodka'],
  rum: ['rum', 'white rum', 'dark rum', 'light rum', 'spiced rum'],
  gin: ['gin'],
  whiskey: ['whiskey', 'bourbon', 'scotch', 'irish whiskey', 'rye whiskey', 'canadian whisky'],
  tequila: ['tequila', 'mezcal'],
  liqueur: [
    // Citrus Liqueurs
    'triple sec',
    'cointreau',
    'grand marnier',
    'blue curacao',
    'orange liqueur',

    // Herbal & Bitter Liqueurs
    'campari',
    'aperol',
    'chartreuse',
    'benedictine',
    'galliano',
    'herbal liqueur',
    'jägermeister',
    'fernet',
    'becherovka',

    // Nut & Coffee Liqueurs
    'amaretto',
    'frangelico',
    'hazelnut liqueur',
    'almond liqueur',
    'baileys',
    'kahlua',
    'coffee liqueur',
    'chocolate liqueur',

    // Fruit Liqueurs
    'chambord',
    'midori',
    'cherry liqueur',
    'raspberry liqueur',
    'melon liqueur',
    'peach liqueur',
    'apricot liqueur',
    'blackberry liqueur',
    'coconut liqueur',

    // Spice & Flavor Liqueurs
    'vanilla liqueur',
    'mint liqueur',
    'ginger liqueur',
    'honey liqueur',
    'maple liqueur',
    'caramel liqueur',
    'butterscotch liqueur',
    'toffee liqueur',
    'cinnamon liqueur',
    'nutmeg liqueur',
    'clove liqueur',
    'allspice liqueur',
    'cardamom liqueur',

    // Floral & Botanical Liqueurs
    'saffron liqueur',
    'lavender liqueur',
    'rose liqueur',
    'elderflower liqueur',
    'hibiscus liqueur',
    'jasmine liqueur',
    'chamomile liqueur',
    'lemongrass liqueur',

    // Asian Spirits & Liqueurs
    'sake',
    'soju',
    'wasabi liqueur',

    // Other European Spirits & Liqueurs
    'schnapps',
    'absinthe',
    'pastis',
    'ouzo',
    'arak',
    'raki',
    'sambuca',
    'kummel',
    'aquavit',
    'akvavit',
    'brennivín',
    'krupnik',
    'krupnikas',
    'nalewka',
    'nalivka',
    'rakia',
    'slivovitz',
    'tsipouro',
    'tsikoudia',
    'zivania',

    // Brandy & Cognac
    'grappa',
    'marc',
    'pomace',
    'brandy',
    'cognac',
    'armagnac',
    'calvados',
    'pisco',

    // Latin American Spirits
    'aguardiente',
    'cachaça',
  ],
};

export const generalIngredients = [
  'whiskey',
  'whisky',
  'rum',
  'gin',
  'vodka',
  'tequila',
  'liqueur',
  'brandy',
  'wine',
  'beer',
  'cider',
  'vermouth',
  'bitters',
  'syrup',
  'juice',
  'soda',
  'water',
  'milk',
  'cream',
  'sugar',
  'honey',
  'spice',
  'herb',
  'fruit',
  'vegetable',
];
